PUT http://localhost:3008/api/snails/6876967ba92c52f9f6426a72
Content-Type: application/json

{
  "name": "Orvar the Steadfast",
  "character": "O",
  "wins": 0,
  "stats": {
    "speed": 4,
    "concentration": 5,
    "adrenalin": -4
  }
}